# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
matrix:
    allow_failures:
      - julia: nightly
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("SweepOperator"); Pkg.test("SweepOperator"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SweepOperator")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
